version: 2
jobs:
  build:
    docker:
      - image: circleci/hashicorp/packer:1.1.1
    steps:
      - checkout
      - run: make 1.13
workflows:
    version: 2
    build-eks-ami:
      jobs:
        - build
